/*
		Project:		Calculator
		Module:			buttons,h
		Description:	Ids for the UI
		Author:			Martin Gäckler
		Address:		Hofmannsthalweg 14, A-4030 Linz
		Web:			https://www.gaeckler.at/

		Copyright:		(c) 1988-2024 Martin Gäckler

		This program is free software: you can redistribute it and/or modify  
		it under the terms of the GNU General Public License as published by  
		the Free Software Foundation, version 3.

		You should have received a copy of the GNU General Public License 
		along with this program. If not, see <http://www.gnu.org/licenses/>.

		THIS SOFTWARE IS PROVIDED BY Martin Gäckler, Austria, Linz ``AS IS''
		AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
		TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
		PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR
		CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
		SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
		LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
		USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
		ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
		OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
		OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
		SUCH DAMAGE.
*/

#define CM_HELPITEM2	3
#define CM_HELPITEM1	2
#define CM_HELPITEM	1
#define CNSTDSP		1
#define INVERS 		2
#define RANDOM 		3
#define XINPUT 		4
#define HYPERBEL 	5
#define DECLOG 		6
#define ABSOLUTE 	7
#define MINP 		8
#define SUMX2 		9
#define DN 			10
#define SINUS 		11
#define NATLOG 		12
#define INTEGER 	13
#define MR 			14
#define SUMX 		15
#define DNMIN1 		16
#define COSINUS 	17
#define REZIPROK 	18
#define FRAC 		19
#define MPLUS 		20
#define NUMBER 		21
#define MEDIUM 		22
#define TANGENS 	23
#define SQRROOT 	24
#define FACULTAT 	25
#define MMINUS 		26
#define FLOATTYP 	27
#define BYTETYPE 	28
#define WORDTYPE 	29
#define LONGTYPE 	30
#define ENGINEER 	31
#define SWAPXM 		32
#define DISPLAY 	33
#define MANTDSP 	34
#define EXPODSP 	35
#define INVDSP 		36
#define HYPDSP 		37
#define TRGDISP 	38
#define MEMDSP 		39
#define STATDSP 	40
#define RADIXDSP 	41
#define TYPEDISP 	42
#define DUALSYS 	43
#define OKTALSYS 	44
#define DEZIMAL 	45
#define HEXSYS 		46
#define ANGLE 		47
#define SWAPXY 		48
#define DIGITF 		49
#define DIGITE 		50
#define DIGITD 		51
#define DIGITC 		52
#define DIGITB 		53
#define DIGITA 		54
#define ROUND 		55
#define OPNBRACK 	56
#define SEVEN 		57
#define FOUR 		58
#define ONE 		59
#define ZERO 		60
#define FIXPOINT 	61
#define CLSBRACK 	62
#define EIGHT 		63
#define FIVE 		64
#define TWO 		65
#define POINT 		66
#define DEGREE 		67
#define CLEAR 		68
#define NINE 		69
#define SIX 		70
#define THREE 		71
#define EXPONENT 	72
#define RADIAL 		73
#define ALLCLR 		74
#define POWER 		75
#define MULTIPLY 	76
#define PLUS 		77
#define SIGN 		78
#define GRADIAL 	79
#define ROOTOPER 	80
#define DIVISION 	81
#define MINUS 		82
#define NOTFUNC 	83
#define MODULOOP 	84
#define ANDOPER 	85
#define XOROPER 	86
#define OROPER 		87
#define EQUAL 		88
#define IDC_BUTTON1	101
#define IDC_STATICTEXT1	101
#define IDC_STATICTEXT2	102
#define BINOM		89
#define YINPUT		90
#define SUMXY		91
#define SUMY		92
#define SUMY2		93
#define CONSTVAL	94
#define REGKOEF		95
#define KORKOEF		96
#define XOUT		97
#define YOUT        98
#define LINEREG		99
#define LNREG		100
#define EXPOREG		101
#define POWEREG		102
#define REGDSP		103
#define BESTMTCH	104
#define C_MANTDSP	105
#define C_EXPODSP	106
#define FRACTION	107
