/*
		Project:		Calculator
		Module:			calh.h
		Description:	Ids for the UI
		Author:			Martin Gäckler
		Address:		Hofmannsthalweg 14, A-4030 Linz
		Web:			https://www.gaeckler.at/

		Copyright:		(c) 1988-2024 Martin Gäckler

		This program is free software: you can redistribute it and/or modify  
		it under the terms of the GNU General Public License as published by  
		the Free Software Foundation, version 3.

		You should have received a copy of the GNU General Public License 
		along with this program. If not, see <http://www.gnu.org/licenses/>.

		THIS SOFTWARE IS PROVIDED BY Martin Gäckler, Austria, Linz ``AS IS''
		AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
		TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
		PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR
		CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
		SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
		LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
		USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
		ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
		OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
		OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
		SUCH DAMAGE.
*/

#define LARGE 0  	/* TREE */
#define GEMMENU 1  	/* TREE */
#define SMALL 2  	/* TREE */
#define SCIENCE 3  	/* TREE */
#define COMPUTER 4  	/* TREE */
#define LINVERS 2  	/* OBJECT in TREE #0 */
#define LRAN 3  	/* OBJECT in TREE #0 */
#define LXINP 4  	/* OBJECT in TREE #0 */
#define LHYPER 5  	/* OBJECT in TREE #0 */
#define LLOG 6  	/* OBJECT in TREE #0 */
#define LABS 7  	/* OBJECT in TREE #0 */
#define LMINP 8  	/* OBJECT in TREE #0 */
#define LSUMSQR 9  	/* OBJECT in TREE #0 */
#define LDN 10  	/* OBJECT in TREE #0 */
#define LSIN 11  	/* OBJECT in TREE #0 */
#define LLN 12  	/* OBJECT in TREE #0 */
#define LINT 13  	/* OBJECT in TREE #0 */
#define LMR 14  	/* OBJECT in TREE #0 */
#define LSUMX 15  	/* OBJECT in TREE #0 */
#define LDNMIN1 16  	/* OBJECT in TREE #0 */
#define LCOS 17  	/* OBJECT in TREE #0 */
#define LREZI 18  	/* OBJECT in TREE #0 */
#define LFRC 19  	/* OBJECT in TREE #0 */
#define LMPLUS 20  	/* OBJECT in TREE #0 */
#define LNUM 21  	/* OBJECT in TREE #0 */
#define LMED 22  	/* OBJECT in TREE #0 */
#define LTAN 23  	/* OBJECT in TREE #0 */
#define LSQR 24  	/* OBJECT in TREE #0 */
#define LFAC 25  	/* OBJECT in TREE #0 */
#define LMMINUS 26  	/* OBJECT in TREE #0 */
#define LFLOAT 27  	/* OBJECT in TREE #0 */
#define LBYTE 28  	/* OBJECT in TREE #0 */
#define LWORD 29  	/* OBJECT in TREE #0 */
#define LLONG 30  	/* OBJECT in TREE #0 */
#define LENG 31  	/* OBJECT in TREE #0 */
#define LSWAPM 32  	/* OBJECT in TREE #0 */
#define LDISPLAY 33  	/* OBJECT in TREE #0 */
#define LINVDSP 34  	/* OBJECT in TREE #0 */
#define LHYPDSP 35  	/* OBJECT in TREE #0 */
#define LTRGDSP 36  	/* OBJECT in TREE #0 */
#define LMEMDSP 37  	/* OBJECT in TREE #0 */
#define LSDSP 38  	/* OBJECT in TREE #0 */
#define LRADXDSP 39  	/* OBJECT in TREE #0 */
#define LTYPEDSP 40  	/* OBJECT in TREE #0 */
#define LMANTDSP 41  	/* OBJECT in TREE #0 */
#define LEXPODSP 42  	/* OBJECT in TREE #0 */
#define LCONST 43  	/* OBJECT in TREE #0 */
#define LDUAL 44  	/* OBJECT in TREE #0 */
#define LOCT 45  	/* OBJECT in TREE #0 */
#define LDEC 46  	/* OBJECT in TREE #0 */
#define LHEX 47  	/* OBJECT in TREE #0 */
#define LANGLE 48  	/* OBJECT in TREE #0 */
#define LSWAP 49  	/* OBJECT in TREE #0 */
#define LDIGITF 50  	/* OBJECT in TREE #0 */
#define LDIGITE 51  	/* OBJECT in TREE #0 */
#define LDIGITD 52  	/* OBJECT in TREE #0 */
#define LDIGITC 53  	/* OBJECT in TREE #0 */
#define LDIGITB 54  	/* OBJECT in TREE #0 */
#define LDIGITA 55  	/* OBJECT in TREE #0 */
#define LRND 56  	/* OBJECT in TREE #0 */
#define LOPENBRK 57  	/* OBJECT in TREE #0 */
#define LSEVEN 58  	/* OBJECT in TREE #0 */
#define LFOUR 59  	/* OBJECT in TREE #0 */
#define LONE 60  	/* OBJECT in TREE #0 */
#define LZERO 61  	/* OBJECT in TREE #0 */
#define LFIX 62  	/* OBJECT in TREE #0 */
#define LCLOSBRK 63  	/* OBJECT in TREE #0 */
#define LEIGHT 64  	/* OBJECT in TREE #0 */
#define LFIVE 65  	/* OBJECT in TREE #0 */
#define LTWO 66  	/* OBJECT in TREE #0 */
#define LPOINT 67  	/* OBJECT in TREE #0 */
#define LDEG 68  	/* OBJECT in TREE #0 */
#define LCLEAR 69  	/* OBJECT in TREE #0 */
#define LNINE 70  	/* OBJECT in TREE #0 */
#define LSIX 71  	/* OBJECT in TREE #0 */
#define LTHREE 72  	/* OBJECT in TREE #0 */
#define LEXPO 73  	/* OBJECT in TREE #0 */
#define LRAD 74  	/* OBJECT in TREE #0 */
#define LALLCLR 75  	/* OBJECT in TREE #0 */
#define LPOWER 76  	/* OBJECT in TREE #0 */
#define LMULTY 77  	/* OBJECT in TREE #0 */
#define LPLUS 78  	/* OBJECT in TREE #0 */
#define LSIGN 79  	/* OBJECT in TREE #0 */
#define LGRA 80  	/* OBJECT in TREE #0 */
#define LROOT 81  	/* OBJECT in TREE #0 */
#define LDIVISIO 82  	/* OBJECT in TREE #0 */
#define LMINUS 83  	/* OBJECT in TREE #0 */
#define LNOT 84  	/* OBJECT in TREE #0 */
#define LMOD 85  	/* OBJECT in TREE #0 */
#define LAND 86  	/* OBJECT in TREE #0 */
#define LXOR 87  	/* OBJECT in TREE #0 */
#define LOR 88  	/* OBJECT in TREE #0 */
#define LEQUAL 89  	/* OBJECT in TREE #0 */
#define CALCMENU 3  	/* OBJECT in TREE #1 */
#define EDITMENU 4  	/* OBJECT in TREE #1 */
#define PANELMEN 5  	/* OBJECT in TREE #1 */
#define CALCPOP 7  	/* OBJECT in TREE #1 */
#define ABOUT 8  	/* OBJECT in TREE #1 */
#define DESK1 10  	/* OBJECT in TREE #1 */
#define DESK2 11  	/* OBJECT in TREE #1 */
#define DESK3 12  	/* OBJECT in TREE #1 */
#define DESK4 13  	/* OBJECT in TREE #1 */
#define DESK5 14  	/* OBJECT in TREE #1 */
#define DESK6 15  	/* OBJECT in TREE #1 */
#define EDITPOP 16  	/* OBJECT in TREE #1 */
#define QUIT 17  	/* OBJECT in TREE #1 */
#define PASTE 19  	/* OBJECT in TREE #1 */
#define COPY 20  	/* OBJECT in TREE #1 */
#define PANELPOP 21  	/* OBJECT in TREE #1 */
#define LARGEPAN 22  	/* OBJECT in TREE #1 */
#define SNCEPAN 23  	/* OBJECT in TREE #1 */
#define COMPPAN 24  	/* OBJECT in TREE #1 */
#define SMALLPAN 25  	/* OBJECT in TREE #1 */
#define SDISPLAY 1  	/* OBJECT in TREE #2 */
#define SMEMDSP 2  	/* OBJECT in TREE #2 */
#define SMANTDSP 3  	/* OBJECT in TREE #2 */
#define SEXPODSP 4  	/* OBJECT in TREE #2 */
#define SCONST 5  	/* OBJECT in TREE #2 */
#define SMINP 7  	/* OBJECT in TREE #2 */
#define SMR 8  	/* OBJECT in TREE #2 */
#define SMPLUS 9  	/* OBJECT in TREE #2 */
#define SMMINUS 10  	/* OBJECT in TREE #2 */
#define SSWAPM 11  	/* OBJECT in TREE #2 */
#define SOPENBRK 12  	/* OBJECT in TREE #2 */
#define SSEVEN 13  	/* OBJECT in TREE #2 */
#define SFOUR 14  	/* OBJECT in TREE #2 */
#define SONE 15  	/* OBJECT in TREE #2 */
#define SZERO 16  	/* OBJECT in TREE #2 */
#define SCLOSBRK 17  	/* OBJECT in TREE #2 */
#define SEIGHT 18  	/* OBJECT in TREE #2 */
#define SFIVE 19  	/* OBJECT in TREE #2 */
#define STWO 20  	/* OBJECT in TREE #2 */
#define SPOINT 21  	/* OBJECT in TREE #2 */
#define SFIX 22  	/* OBJECT in TREE #2 */
#define SCLEAR 23  	/* OBJECT in TREE #2 */
#define SNINE 24  	/* OBJECT in TREE #2 */
#define SSIX 25  	/* OBJECT in TREE #2 */
#define STHREE 26  	/* OBJECT in TREE #2 */
#define SEXPO 27  	/* OBJECT in TREE #2 */
#define SRND 28  	/* OBJECT in TREE #2 */
#define SALLCLR 29  	/* OBJECT in TREE #2 */
#define SPOWER 30  	/* OBJECT in TREE #2 */
#define SMULTY 31  	/* OBJECT in TREE #2 */
#define SPLUS 32  	/* OBJECT in TREE #2 */
#define SSIGN 33  	/* OBJECT in TREE #2 */
#define SSWAP 34  	/* OBJECT in TREE #2 */
#define SROOT 35  	/* OBJECT in TREE #2 */
#define SDIVISIO 36  	/* OBJECT in TREE #2 */
#define SMINUS 37  	/* OBJECT in TREE #2 */
#define SEQUAL 38  	/* OBJECT in TREE #2 */
#define EINVERS 1  	/* OBJECT in TREE #3 */
#define EENG 2  	/* OBJECT in TREE #3 */
#define EXINP 3  	/* OBJECT in TREE #3 */
#define EYINP 4  	/* OBJECT in TREE #3 */
#define ECNSTVAL 5  	/* OBJECT in TREE #3 */
#define EHYPER 6  	/* OBJECT in TREE #3 */
#define ELOG 7  	/* OBJECT in TREE #3 */
#define ELINREG 9  	/* OBJECT in TREE #3 */
#define EDN 10  	/* OBJECT in TREE #3 */
#define ESUMX2 11  	/* OBJECT in TREE #3 */
#define ESUMY2 12  	/* OBJECT in TREE #3 */
#define EREGKOEF 13  	/* OBJECT in TREE #3 */
#define ESIN 14  	/* OBJECT in TREE #3 */
#define ELN 15  	/* OBJECT in TREE #3 */
#define ELNREG 16  	/* OBJECT in TREE #3 */
#define EDNMIN1 17  	/* OBJECT in TREE #3 */
#define ESUMX 18  	/* OBJECT in TREE #3 */
#define ESUMY 19  	/* OBJECT in TREE #3 */
#define EKORKOEF 20  	/* OBJECT in TREE #3 */
#define ECOS 21  	/* OBJECT in TREE #3 */
#define EREZI 22  	/* OBJECT in TREE #3 */
#define EEXPREG 23  	/* OBJECT in TREE #3 */
#define EMED 24  	/* OBJECT in TREE #3 */
#define ENUM 25  	/* OBJECT in TREE #3 */
#define ESUMXY 26  	/* OBJECT in TREE #3 */
#define EBSTMTCH 27  	/* OBJECT in TREE #3 */
#define ETAN 28  	/* OBJECT in TREE #3 */
#define EFAC 29  	/* OBJECT in TREE #3 */
#define EPOWREG 30  	/* OBJECT in TREE #3 */
#define ERAN 31  	/* OBJECT in TREE #3 */
#define EXOUT 32  	/* OBJECT in TREE #3 */
#define EYOUT 33  	/* OBJECT in TREE #3 */
#define EANGLE 34  	/* OBJECT in TREE #3 */
#define ESQR 35  	/* OBJECT in TREE #3 */
#define EBINOM 36  	/* OBJECT in TREE #3 */
#define EDISPLAY 37  	/* OBJECT in TREE #3 */
#define EINVDSP 38  	/* OBJECT in TREE #3 */
#define EHYPDSP 39  	/* OBJECT in TREE #3 */
#define ETRGDSP 40  	/* OBJECT in TREE #3 */
#define EMEMDSP 41  	/* OBJECT in TREE #3 */
#define ESDSP 42  	/* OBJECT in TREE #3 */
#define EMANTDSP 43  	/* OBJECT in TREE #3 */
#define EEXPODSP 44  	/* OBJECT in TREE #3 */
#define ECONST 45  	/* OBJECT in TREE #3 */
#define EREGDSP 46  	/* OBJECT in TREE #3 */
#define EABS 47  	/* OBJECT in TREE #3 */
#define EOPENBRK 48  	/* OBJECT in TREE #3 */
#define ESEVEN 49  	/* OBJECT in TREE #3 */
#define EFOUR 50  	/* OBJECT in TREE #3 */
#define EONE 51  	/* OBJECT in TREE #3 */
#define EZERO 52  	/* OBJECT in TREE #3 */
#define EINT 53  	/* OBJECT in TREE #3 */
#define ECLOSBRK 54  	/* OBJECT in TREE #3 */
#define EEIGHT 55  	/* OBJECT in TREE #3 */
#define EFIVE 56  	/* OBJECT in TREE #3 */
#define ETWO 57  	/* OBJECT in TREE #3 */
#define EPOINT 58  	/* OBJECT in TREE #3 */
#define EFRC 59  	/* OBJECT in TREE #3 */
#define ECLEAR 60  	/* OBJECT in TREE #3 */
#define ENINE 61  	/* OBJECT in TREE #3 */
#define ESIX 62  	/* OBJECT in TREE #3 */
#define ETHREE 63  	/* OBJECT in TREE #3 */
#define EEXPO 64  	/* OBJECT in TREE #3 */
#define EDEG 65  	/* OBJECT in TREE #3 */
#define ERND 66  	/* OBJECT in TREE #3 */
#define EALLCLR 67  	/* OBJECT in TREE #3 */
#define EPOWER 68  	/* OBJECT in TREE #3 */
#define EMULTY 69  	/* OBJECT in TREE #3 */
#define EPLUS 70  	/* OBJECT in TREE #3 */
#define ESIGN 71  	/* OBJECT in TREE #3 */
#define ERAD 72  	/* OBJECT in TREE #3 */
#define EFIX 73  	/* OBJECT in TREE #3 */
#define EROOT 74  	/* OBJECT in TREE #3 */
#define EDIVISIO 75  	/* OBJECT in TREE #3 */
#define EMINUS 76  	/* OBJECT in TREE #3 */
#define EEQUAL 77  	/* OBJECT in TREE #3 */
#define EGRA 78  	/* OBJECT in TREE #3 */
#define EMINP 79  	/* OBJECT in TREE #3 */
#define EMR 80  	/* OBJECT in TREE #3 */
#define EMPLUS 81  	/* OBJECT in TREE #3 */
#define EMMINUS 82  	/* OBJECT in TREE #3 */
#define ESWAPM 83  	/* OBJECT in TREE #3 */
#define ESWAP 84  	/* OBJECT in TREE #3 */
#define CDISPLAY 1  	/* OBJECT in TREE #4 */
#define CINVDSP 2  	/* OBJECT in TREE #4 */
#define CMEMDSP 3  	/* OBJECT in TREE #4 */
#define CRADXDSP 4  	/* OBJECT in TREE #4 */
#define CTYPEDSP 5  	/* OBJECT in TREE #4 */
#define CMANTDSP 7  	/* OBJECT in TREE #4 */
#define CEXPODSP 8  	/* OBJECT in TREE #4 */
#define CCONST 9  	/* OBJECT in TREE #4 */
#define CINVERS 10  	/* OBJECT in TREE #4 */
#define CBYTE 11  	/* OBJECT in TREE #4 */
#define CWORD 12  	/* OBJECT in TREE #4 */
#define CLONG 13  	/* OBJECT in TREE #4 */
#define CFLOAT 14  	/* OBJECT in TREE #4 */
#define CDUAL 15  	/* OBJECT in TREE #4 */
#define CDEC 16  	/* OBJECT in TREE #4 */
#define CFIX 17  	/* OBJECT in TREE #4 */
#define CRND 18  	/* OBJECT in TREE #4 */
#define CINT 19  	/* OBJECT in TREE #4 */
#define CFRC 20  	/* OBJECT in TREE #4 */
#define CABS 21  	/* OBJECT in TREE #4 */
#define COCT 22  	/* OBJECT in TREE #4 */
#define CHEX 23  	/* OBJECT in TREE #4 */
#define CMINP 24  	/* OBJECT in TREE #4 */
#define COPENBRK 25  	/* OBJECT in TREE #4 */
#define CSEVEN 26  	/* OBJECT in TREE #4 */
#define CFOUR 27  	/* OBJECT in TREE #4 */
#define CONE 28  	/* OBJECT in TREE #4 */
#define CZERO 29  	/* OBJECT in TREE #4 */
#define CDIGITA 30  	/* OBJECT in TREE #4 */
#define CMR 31  	/* OBJECT in TREE #4 */
#define CCLOSBRK 32  	/* OBJECT in TREE #4 */
#define CEIGHT 33  	/* OBJECT in TREE #4 */
#define CFIVE 34  	/* OBJECT in TREE #4 */
#define CTWO 35  	/* OBJECT in TREE #4 */
#define CPOINT 36  	/* OBJECT in TREE #4 */
#define CDIGITB 37  	/* OBJECT in TREE #4 */
#define CMPLUS 38  	/* OBJECT in TREE #4 */
#define CCLEAR 39  	/* OBJECT in TREE #4 */
#define CNINE 40  	/* OBJECT in TREE #4 */
#define CSIX 41  	/* OBJECT in TREE #4 */
#define CTHREE 42  	/* OBJECT in TREE #4 */
#define CEXPO 43  	/* OBJECT in TREE #4 */
#define CDIGITC 44  	/* OBJECT in TREE #4 */
#define CMMINUS 45  	/* OBJECT in TREE #4 */
#define CALLCLR 46  	/* OBJECT in TREE #4 */
#define CPOWER 47  	/* OBJECT in TREE #4 */
#define CMULTY 48  	/* OBJECT in TREE #4 */
#define CPLUS 49  	/* OBJECT in TREE #4 */
#define CSIGN 50  	/* OBJECT in TREE #4 */
#define CDIGITD 51  	/* OBJECT in TREE #4 */
#define CSWAPM 52  	/* OBJECT in TREE #4 */
#define CROOT 53  	/* OBJECT in TREE #4 */
#define CDIVISIO 54  	/* OBJECT in TREE #4 */
#define CMINUS 55  	/* OBJECT in TREE #4 */
#define CNOT 56  	/* OBJECT in TREE #4 */
#define CDIGITE 57  	/* OBJECT in TREE #4 */
#define CSWAP 58  	/* OBJECT in TREE #4 */
#define CMOD 59  	/* OBJECT in TREE #4 */
#define CAND 60  	/* OBJECT in TREE #4 */
#define CXOR 61  	/* OBJECT in TREE #4 */
#define COR 62  	/* OBJECT in TREE #4 */
#define CEQUAL 63  	/* OBJECT in TREE #4 */
#define CDIGITF 64  	/* OBJECT in TREE #4 */
